# Generated by Django 4.1.4 on 2023-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_location', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('travellers', models.IntegerField()),
                ('estimation', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PastTravelledTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_location', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('travellers', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
