# Generated by Django 4.1.8 on 2023-04-18 04:50

import apptrip.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftrip', djongo.models.fields.EmbeddedField(model_container=apptrip.models.FutureTrips)),
                ('build', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FutureTrips',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Place_name', models.CharField(max_length=100)),
                ('Start_date', models.DateField(blank=True, null=True)),
                ('End_date', models.DateField(blank=True, null=True)),
                ('Email', models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PastTravelledTrips',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Place_name', models.CharField(max_length=100)),
                ('Start_date', models.DateField(blank=True, null=True)),
                ('End_date', models.DateField(blank=True, null=True)),
                ('Email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptrip', djongo.models.fields.EmbeddedField(model_container=apptrip.models.PastTravelledTrips)),
                ('headline', models.CharField(max_length=225)),
            ],
        ),
    ]
