# Generated by Django 4.1.4 on 2023-02-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuretrips',
            name='estimation',
        ),
        migrations.RemoveField(
            model_name='futuretrips',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pasttravelledtrips',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='pasttravelledtrips',
            name='id',
        ),
        migrations.AlterField(
            model_name='futuretrips',
            name='travellers',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pasttravelledtrips',
            name='travellers',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
