# Generated by Django 4.1.4 on 2023-02-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0002_remove_futuretrips_estimation_remove_futuretrips_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuretrips',
            old_name='travellers',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pasttravelledtrips',
            old_name='travellers',
            new_name='id',
        ),
    ]
