# Generated by Django 4.1.4 on 2023-02-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0003_rename_travellers_futuretrips_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuretrips',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='pasttravelledtrips',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
