# Generated by Django 4.1.4 on 2023-02-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0004_futuretrips_email_pasttravelledtrips_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuretrips',
            old_name='duration',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='pasttravelledtrips',
            old_name='duration',
            new_name='people',
        ),
    ]
