# Generated by Django 4.1.4 on 2023-02-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0005_rename_duration_futuretrips_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuretrips',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pasttravelledtrips',
            name='email',
        ),
    ]
