# Generated by Django 4.1.4 on 2023-02-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0006_remove_futuretrips_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasttravelledtrips',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
