# Generated by Django 4.1.4 on 2023-02-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0007_pasttravelledtrips_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasttravelledtrips',
            name='cost',
            field=models.IntegerField(default=4000),
        ),
    ]
