# Generated by Django 4.1.4 on 2023-02-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0008_pasttravelledtrips_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuretrips',
            old_name='trip_location',
            new_name='trip_name',
        ),
        migrations.RenameField(
            model_name='pasttravelledtrips',
            old_name='trip_location',
            new_name='trip_name',
        ),
        migrations.AddField(
            model_name='futuretrips',
            name='cost',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='futuretrips',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
