# Generated by Django 4.1.4 on 2023-02-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0009_rename_trip_location_futuretrips_trip_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuretrips',
            name='duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pasttravelledtrips',
            name='duration',
            field=models.IntegerField(default=None),
        ),
    ]
