# Generated by Django 4.1.4 on 2023-02-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0010_futuretrips_duration_pasttravelledtrips_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuretrips',
            old_name='cost',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='pasttravelledtrips',
            old_name='cost',
            new_name='budget',
        ),
    ]
