# Generated by Django 4.1.4 on 2023-02-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0011_rename_cost_futuretrips_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuretrips',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
