# Generated by Django 4.1.4 on 2023-03-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0013_rename_trip_name_futuretrips_place_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuretrips',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='pasttravelledtrips',
            old_name='email',
            new_name='Email',
        ),
    ]
