# Generated by Django 4.1.4 on 2023-03-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0014_rename_email_futuretrips_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuretrips',
            name='Email',
            field=models.EmailField(max_length=70),
        ),
    ]
