# Generated by Django 4.1.4 on 2023-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0015_alter_futuretrips_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuretrips',
            name='End_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futuretrips',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pasttravelledtrips',
            name='End_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pasttravelledtrips',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
